### ISSUE TITLE
nice work,why not publish on CRAN? 

### ISSUE THREAD

**Issue by RyanLee-Dev** [RMHogervorst/imdb#10]
nice work,why not publish on CRAN?

**Comment by RMHogervorst** [comment]
Hi liyuan,

Thank you! 
I considered it, but I thought no one used it, however, peopledo seem to use it so I might consider it.
What would be the benefit for you?

- Roel

**Comment by RMHogervorst** [comment]
Hi @liyuan97 , 
I'm closing this issue since you do not respond. Feel free to update the issue and reopen it again.
