### ISSUE TITLE
Key is needed

### ISSUE THREAD

**Issue by thehappyapple** [RMHogervorst/imdb#11]
I need to add a key but I do not how! Can you explain it?

**Comment by RMHogervorst** [comment]
Yes, I probably need to add it to the readme too. But I'd be happy if you helped out? 
See also #4 

First you need a key. The omdbapi requires a api key to function. 
Go to <https://www.omdbapi.com/apikey.aspx> and apply for a key (use the free one or support the developer with patreon) . 
After you've recieved the key save it in your session or script [1].

Below is an example that should work for you.

```
library(imdb)
key <- put your key here
movies <- imdbMovies(moviename = "moviename", key = key)
series <- imdbSeries("seryname", key = key)
```


[1]:  This is not ideal, I'm working on a different solution where you place the api somewhere else and R reads it in.

**Comment by RMHogervorst** [comment]
should now be more clear #12
