### ISSUE TITLE
imdbmovies(search_by_title_id)

### ISSUE THREAD

**Issue by p3lewis** [RMHogervorst/imdb#13]
Hi Roel, is it difficult for you to support a search by IMDB title id?

P.S. this is really amazing work you've done here.

--
Phill

**Comment by RMHogervorst** [comment]
Hi phill,

I don't know actually. I'll have to check out the api. Remind me in a week if you haven't heard. Or create a pull request if you have a solution. Thanks for the issue!

**Comment by p3lewis** [comment]
I'm still learning so I'm not sure I can do this yet. Will follow up next week.

**Comment by RMHogervorst** [comment]
We are all learning, so don't feel bad! I can tell you everyone of people you follow on github is still learning stuff after years of work. There are mountains of knowledge and only so many we can climb.

**Comment by RMHogervorst** [comment]
Ah I think it will be relatively easy (for me)! 

https://www.omdbapi.com/#parameters
says there are two parameters: 

- I use t= (movie title)
- other is i=  A valid IMDb ID (e.g. tt1285016)

I can create a new function that accepts the i.

**Comment by RMHogervorst** [comment]
should work for you now
