### ISSUE TITLE
ToS violation notice

### ISSUE THREAD

**Issue by hrbrmstr** [RMHogervorst/imdb#6]
Please consider adding a message to every interactive API call that folks who use this are in violation of the Terms of Service for IMDB. 

LinkedIn and 2 other companies started aggressively issuing lawsuits for scrapers and Amazon has the capacity (I work with various Amazon AWS team members/departments in my role at Rapid7) to both track these scrapings and issue C&D's as well as lawsuits.

I appreciate the work you're doing here, do not agree with the ToS silliness but like to play within the rules. 

I just don't want to see individuals use this w/o realizing the ToS violation and def do not want to see you potentially get dragged into anything as an enabler.

**Comment by RMHogervorst** [comment]
Thanks for the notice, I will add a message
