### ISSUE TITLE
Open Connection Error when calling imdbMovies()

### ISSUE THREAD

**Issue by p3lewis** [RMHogervorst/imdb#8]
Ran this:

> library(imdb)
> testdata = imdbMovies("The Post")
Error in open.connection(con, "rb") : HTTP error 401.

Any ideas?

**Comment by RMHogervorst** [comment]
First of all, thank you for reporting this issue! 
The 401 is a web error code and means that he action is not allowed. 
The service I call in this package  http://www.omdbapi.com is not down, but requires an API key. 
I will update the package to deal with this change.

**Comment by RMHogervorst** [comment]
but it will take at least a week, because I have to rewrite the api calls. (I build this when I was just starting out in R)

**Comment by RMHogervorst** [comment]
If you 'd like you could help?
development is in the api_key

**Comment by p3lewis** [comment]
I would love to help, but I don't know much about R programming as yet. I don't feel comfortable. I can wait the week for it.

Though, if you really need my help, I will try to work on it. Lmk if so.

**Comment by joshyazman** [comment]
Hi @RMHogervorst - I submitted a pull request that I think will fix this for the `imdbSeries()` function. It'll probably work the same way for the other two!

**Comment by RMHogervorst** [comment]
Ooohn thanks! I will check it out

**Comment by RMHogervorst** [comment]
This should now work @p3lewis ! 

Thank you @joshyazman !

**Comment by p3lewis** [comment]
@RMHogervorst , @joshyazman  -- would like to thank you both very specially! I appreciate it. People like you keep the free flow of information. 

Thank you!
